python3 main.py \
    --exp_name sample_experiment \
    --dataset_root /home/amin/Documents/projects/SignSGDVariant/datasets/mnist \
    --model vanilla_cnn \
    --dataset MNIST \
    --optimizer sign_sgd \
    --batch_size 8 \
    --epochs 10 \
    --lr 0.1 \
    --num_bits 2 \
    --binning lin \
    --rand_zero True \
    --step_size 1
