python3 main.py \
    --exp_name sample_experiment \
    --dataset_root /home/amin/Documents/projects/SignSGDVariant/datasets/mnist \
    --model vanilla_cnn \
    --dataset MNIST \
    --optimizer compressed_sgd \
    --batch_size 64 \
    --epochs 1 \
    --weight_decay 0.8 0.5\
    --lr 0.01 \
    --num_bits 3 \
    --binning lin \
    --num_workers 1 \
    --batchwise_evaluation False\
    --rand_zero True
